/// <reference lib="webworker" />
import type { DecisionReadout } from "../brain/activation";
import { quantize, topNeurons, summarizeRegions } from "../brain/activation";
import type { MoveTrace } from "../traces/MoveTrace";
import { FrameStreamTracker } from "./frameStream";
import { modelTruthBadge } from "./modelTruth";
import type { ModelManifestInfo, StockFlyRequest, StockFlyResponse, TraceVerification } from "./protocol";
import { compareRecordedActivation, CPU_DECISION_TOLERANCE } from "./traceVerification";
// Generated by `wasm-pack build` from crates/stockfly-wasm (see that
// crate's Cargo.toml); this directory is build output, not committed
// (wasm-gen/.gitignore), and lives under src/ rather than public/ so Vite
// can statically bundle it and correctly rewrite its internal
// `fetch(new URL('stockfly_wasm_bg.wasm', import.meta.url))` call.
// @ts-ignore -- generated types, not present until the crate is built.
import init, { StockFlyEngine } from "../wasm-gen/stockfly_wasm.js";

import { parseAnnotations } from "../brain/geometry";

let engine: StockFlyEngine | null = null;
let generation = 0;
let regions: string[] | null = null;
let queue = Promise.resolve();
let loadedManifest: ModelManifestInfo | null = null;

interface RawDecision {
  selected_move: string;
  from_rates: number[];
  to_rates: number[];
  promotion_rates: number[];
  legal_scores: Array<[string, number]>;
  graph_neurons_sha256?: string;
  sensory_map_sha256?: string;
  output_map_sha256?: string;
  backend?: string;
  adapter?: string;
  gpu_fallback_reason?: string;
  model_label?: string;
}

async function sha256(text: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, "0")).join("");
}

function readout(raw: RawDecision): DecisionReadout {
  return {
    selectedMove: raw.selected_move,
    fromRates: raw.from_rates,
    toRates: raw.to_rates,
    promotionRates: raw.promotion_rates,
    legalScores: raw.legal_scores.map(([move, score]) => ({ move, score })),
  };
}

function maxDifference(left: number[], right: number[]): number {
  if (left.length !== right.length) return Infinity;
  let maximum = 0;
  for (let index = 0; index < left.length; index++) maximum = Math.max(maximum, Math.abs(left[index] - right[index]));
  return maximum;
}

async function fetchRequired(url: string): Promise<Response> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Failed to load ${url}: HTTP ${response.status}`);
  return response;
}

async function concatBlocks(dir: string, filenames: string[]): Promise<Uint8Array> {
  const parts: Uint8Array[] = [];
  let total = 0;
  for (const name of filenames) {
    const res = await fetch(`${dir}/${name}`);
    if (!res.ok) throw new Error(`failed to fetch ${dir}/${name}: ${res.status}`);
    const buf = new Uint8Array(await res.arrayBuffer());
    parts.push(buf);
    total += buf.length;
  }
  const out = new Uint8Array(total);
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.length;
  }
  return out;
}

async function loadEngine(requestGeneration: number) {
  await init();

  const manifestRes = await fetchRequired("/vendor/graph/manifest.json");
  const manifestText = await manifestRes.text();
  const manifest = JSON.parse(manifestText);

  const neuronsRes = await fetchRequired("/vendor/graph/neurons.bin");
  const offsetsRes = await fetchRequired("/vendor/graph/offsets.bin");
  const neurons = new Uint8Array(await neuronsRes.arrayBuffer());
  const offsets = new Uint8Array(await offsetsRes.arrayBuffer());

  const blocks = [...manifest.edge_blocks].sort((a: { index: number }, b: { index: number }) => a.index - b.index);
  const srcNames = blocks.map((b: { index: number }) => `edge_src_blocks/${String(b.index).padStart(4, "0")}.bin`);
  const weightNames = blocks.map((b: { index: number }) => `edge_weight_blocks/${String(b.index).padStart(4, "0")}.bin`);
  const edgeSrc = await concatBlocks("/vendor/graph", srcNames);
  const edgeWeight = await concatBlocks("/vendor/graph", weightNames);

  const sensoryJson = await (await fetchRequired("/vendor/chess-maps/sensory-map.json")).text();
  const outputJson = await (await fetchRequired("/vendor/chess-maps/output-map.json")).text();

  engine = new StockFlyEngine(manifestText, neurons, offsets, edgeSrc, edgeWeight, sensoryJson, outputJson);

  // Only a genuine 404 means no trained model. Corrupt checkpoints and
  // network failures are actionable load errors, never a silent baseline.
  const checkpointRes = await fetch("/vendor/checkpoints/stockfly-bio-full.sfckpt");
  let checkpointSha256: string | null = null;
  if (checkpointRes.ok) {
    const checkpointText = await checkpointRes.text();
    engine.load_checkpoint(checkpointText);
    checkpointSha256 = await sha256(checkpointText);
  }
  else if (checkpointRes.status !== 404) throw new Error(`Checkpoint HTTP ${checkpointRes.status}`);

  // Annotations are optional for chess inference. The brain panel reports
  // unavailable/corrupt metadata; do not invent regions when it is missing.
  regions = null;
  try {
    const metadata = await (await fetchRequired("/vendor/brain/metadata.json")).json();
    regions = parseAnnotations(metadata, engine.neuron_count(), manifest.neurons_sha256).map(row => row[3]);
  } catch { /* Frames explicitly carry no region summaries without annotations. */ }

  const backend = JSON.parse(await engine.initialize_gpu());

  const modelLabel = engine.model_label();
  loadedManifest = {
    neuronCount: engine.neuron_count(),
    edgeCount: engine.edge_count(),
    graphNeuronsSha256: manifest.neurons_sha256,
    graphManifestSha256: await sha256(manifestText),
    sensoryMapSha256: await sha256(sensoryJson),
    outputMapSha256: await sha256(outputJson),
    checkpointSha256,
    modelLabel,
    modelBadge: modelTruthBadge(modelLabel),
    backend: backend.backend,
    adapter: backend.adapter,
    ...(backend.fallback_reason ? { fallbackReason: backend.fallback_reason } : {}),
  };
  post({
    type: "loaded",
    generation: requestGeneration,
    manifest: loadedManifest,
  });
}

function post(msg: StockFlyResponse, transfer: Transferable[] = []) {
  (self as unknown as Worker).postMessage(msg, transfer);
}

async function verifyTrace(trace: MoveTrace): Promise<TraceVerification> {
  if (!engine || !loadedManifest) throw new Error("Engine not loaded yet");
  const provenance = trace.provenance;
  const provenanceMatches = provenance.modelKind === loadedManifest.modelLabel
    && provenance.checkpointSha256 === loadedManifest.checkpointSha256
    && provenance.graphManifestSha256 === loadedManifest.graphManifestSha256
    && provenance.graphNeuronsSha256 === loadedManifest.graphNeuronsSha256
    && provenance.sensoryMapSha256 === loadedManifest.sensoryMapSha256
    && provenance.outputMapSha256 === loadedManifest.outputMapSha256;
  if (!provenanceMatches) throw new Error("Trace model/checkpoint/graph/map provenance does not match the loaded engine");
  let frameIndex = 0;
  let decisionPathMatches = true;
  let maxActivationDifference = 0;
  let maxDecisionRateDifference = 0;
  let activationTolerance = CPU_DECISION_TOLERANCE;
  let activationFramesMatch = true;
  let failedActivationFrameCount = 0;
  const cpuFrames: Array<{ step: number; rates: Float32Array; decision: DecisionReadout }> = [];
  const raw = await engine.infer_cpu_stream(
    provenance.inputFen,
    trace.finalDecision.settleSteps,
    (step: number, _tMs: number, rates: Float32Array, _backend: string, decisionJson: string) => {
      const actual = readout(JSON.parse(decisionJson) as RawDecision);
      cpuFrames.push({ step, rates: rates.slice(), decision: actual });
      const expected = trace.frames[frameIndex++];
      if (!expected || expected.step !== step) {
        decisionPathMatches = false;
        activationFramesMatch = false;
        failedActivationFrameCount++;
        maxActivationDifference = Infinity;
        return;
      }
      const activation = compareRecordedActivation(expected.neuronRates, rates);
      activationTolerance = Math.max(activationTolerance, activation.tolerance);
      maxActivationDifference = Math.max(maxActivationDifference, activation.maxDifference);
      activationFramesMatch &&= activation.matches;
      if (!activation.matches) failedActivationFrameCount++;
      decisionPathMatches &&= actual.selectedMove === expected.decision.selectedMove;
      maxDecisionRateDifference = Math.max(
        maxDecisionRateDifference,
        maxDifference(actual.fromRates, expected.decision.fromRates),
        maxDifference(actual.toRates, expected.decision.toRates),
        maxDifference(actual.promotionRates, expected.decision.promotionRates),
      );
    },
  );
  if (frameIndex !== trace.frames.length) {
    decisionPathMatches = false;
    activationFramesMatch = false;
    failedActivationFrameCount += Math.max(0, trace.frames.length - frameIndex);
  }
  const finalRaw = JSON.parse(raw) as RawDecision;
  const final = readout(finalRaw);
  const finalMoveMatches = final.selectedMove === trace.finalDecision.selectedMove;
  maxDecisionRateDifference = Math.max(
    maxDecisionRateDifference,
    maxDifference(final.fromRates, trace.finalDecision.fromRates),
    maxDifference(final.toRates, trace.finalDecision.toRates),
    maxDifference(final.promotionRates, trace.finalDecision.promotionRates),
  );
  const mode = provenance.backend === "cpu-wasm" ? "cpu-replay" : "cpu-reference";
  const recordedTraceMatches = decisionPathMatches && finalMoveMatches
    && activationFramesMatch
    && maxDecisionRateDifference <= CPU_DECISION_TOLERANCE;
  let replayFrameIndex = 0;
  let cpuReplayPathMatches = true;
  let maxCpuReplayActivationDifference = 0;
  let maxCpuReplayDecisionRateDifference = 0;
  const replayRaw = await engine.infer_cpu_stream(
    provenance.inputFen,
    trace.finalDecision.settleSteps,
    (step: number, _tMs: number, rates: Float32Array, _backend: string, decisionJson: string) => {
      const reference = cpuFrames[replayFrameIndex++];
      const replay = readout(JSON.parse(decisionJson) as RawDecision);
      if (!reference || reference.step !== step || reference.rates.length !== rates.length) {
        cpuReplayPathMatches = false;
        maxCpuReplayActivationDifference = Infinity;
        return;
      }
      for (let index = 0; index < rates.length; index++) {
        maxCpuReplayActivationDifference = Math.max(maxCpuReplayActivationDifference, Math.abs(rates[index] - reference.rates[index]));
      }
      cpuReplayPathMatches &&= replay.selectedMove === reference.decision.selectedMove;
      maxCpuReplayDecisionRateDifference = Math.max(
        maxCpuReplayDecisionRateDifference,
        maxDifference(replay.fromRates, reference.decision.fromRates),
        maxDifference(replay.toRates, reference.decision.toRates),
        maxDifference(replay.promotionRates, reference.decision.promotionRates),
      );
    },
  );
  if (replayFrameIndex !== cpuFrames.length) cpuReplayPathMatches = false;
  const replayFinal = readout(JSON.parse(replayRaw) as RawDecision);
  cpuReplayPathMatches &&= replayFinal.selectedMove === final.selectedMove;
  maxCpuReplayDecisionRateDifference = Math.max(
    maxCpuReplayDecisionRateDifference,
    maxDifference(replayFinal.fromRates, final.fromRates),
    maxDifference(replayFinal.toRates, final.toRates),
    maxDifference(replayFinal.promotionRates, final.promotionRates),
  );
  const cpuReplayPassed = cpuReplayPathMatches
    && maxCpuReplayActivationDifference <= CPU_DECISION_TOLERANCE
    && maxCpuReplayDecisionRateDifference <= CPU_DECISION_TOLERANCE;
  const passed = provenanceMatches && cpuReplayPassed && (mode === "cpu-replay" ? recordedTraceMatches : true);
  return {
    mode, passed, provenanceMatches, decisionPathMatches, finalMoveMatches,
    expectedMove: trace.finalDecision.selectedMove, actualMove: final.selectedMove,
    maxActivationDifference, activationTolerance, failedActivationFrameCount,
    maxDecisionRateDifference, decisionRateTolerance: CPU_DECISION_TOLERANCE,
    cpuReplayPassed, recordedTraceMatches,
    maxCpuReplayActivationDifference, maxCpuReplayDecisionRateDifference,
    note: mode === "cpu-replay"
      ? "Deterministic CPU re-simulation of every recorded sample and policy readout."
      : "Repeated CPU runs test CPU path reproducibility. The recorded GPU comparison is reported separately and does not establish general full-graph GPU/CPU parity.",
  };
}

async function handle(req: Exclude<StockFlyRequest, { type: "reset" }>) {
  if (req.generation !== generation) return;
  try {
    if (req.type === "load") {
      engine?.free();
      engine = null;
      loadedManifest = null;
      await loadEngine(req.generation);
    } else if (req.type === "verify-trace") {
      post({ type: "verification", generation: req.generation, verificationId: req.verificationId, result: await verifyTrace(req.trace) });
    } else {
      if (!engine) throw new Error("Engine not loaded yet");
      const settleSteps = req.settleSteps ?? 16;
      if (!Number.isInteger(settleSteps) || settleSteps < 1 || settleSteps > 4096) throw new Error("Invalid settle steps");
      const started = performance.now();
      let lastPosted = -Infinity;
      const stream = new FrameStreamTracker();
      const raw = await engine.infer_stream(req.fen, settleSteps,
        async (step: number, tMs: number, rates: Float32Array, backend: string, decisionJson: string) => {
          const observed = stream.observe({ step, backend });
          if (observed.restarted) {
            lastPosted = -Infinity;
            post({ type: "frame-restart", generation: req.generation, traceId: req.traceId,
              attempt: observed.attempt, backend });
          }
          // Yield between real samples: lets resets cancel CPU and GPU work
          // and limits transferred visualization updates to at most 25 Hz.
          await new Promise(resolve => setTimeout(resolve, Math.max(0, 40 - (performance.now() - lastPosted))));
          if (req.generation !== generation) throw new Error("Obsolete inference");
          const top = topNeurons(rates);
          const regionRates = regions ? summarizeRegions(rates, regions) : [];
          const neuronRates = req.frameMode === "full" ? rates : quantize(rates);
          const buffer = neuronRates instanceof Float32Array ? neuronRates.buffer : neuronRates.values.buffer;
          lastPosted = performance.now();
          post({ type: "frame", generation: req.generation, traceId: req.traceId, attempt: observed.attempt,
            frame: { step, tMs, elapsedMs: lastPosted - started, backend, neuronRates, topNeurons: top, regionRates,
              decision: readout(JSON.parse(decisionJson) as RawDecision) } }, [buffer]);
        });
      if (req.generation !== generation) return;
      const result = JSON.parse(raw);
      post({
        type: "decision", generation: req.generation,
        traceId: req.traceId,
        selectedMove: result.selected_move,
        legalScores: result.legal_scores.map(([move, score]: [string, number]) => ({ move, score })),
        fromRates: result.from_rates,
        toRates: result.to_rates,
        promotionRates: result.promotion_rates,
        settleSteps,
        graphNeuronsSha256: result.graph_neurons_sha256,
        graphManifestSha256: loadedManifest!.graphManifestSha256,
        sensoryMapSha256: result.sensory_map_sha256,
        outputMapSha256: result.output_map_sha256,
        checkpointSha256: loadedManifest!.checkpointSha256,
        backend: result.backend,
        adapter: result.adapter,
        ...(result.gpu_fallback_reason ? { fallbackReason: result.gpu_fallback_reason } : {}),
        modelLabel: result.model_label,
      });
    }
  } catch (e) {
    if (req.generation !== generation) return;
    post({ type: "error", generation: req.generation,
      ...(req.type === "position" ? { traceId: req.traceId } : {}),
      ...(req.type === "verify-trace" ? { verificationId: req.verificationId } : {}),
      message: e instanceof Error ? e.message : String(e) });
  }
}

self.addEventListener("message", (event: MessageEvent<StockFlyRequest>) => {
  const req = event.data;
  // Invalidate immediately; engine mutation remains strictly serialized.
  if (req.type === "reset") { generation = req.generation; return; }
  if (req.type === "load") generation = req.generation;
  queue = queue.then(() => handle(req));
});
