/// <reference lib="webworker" />
import type { StockFlyRequest, StockFlyResponse } from "./protocol";
// Generated by `wasm-pack build` from crates/stockfly-wasm (see that
// crate's Cargo.toml); this directory is build output, not committed
// (wasm-gen/.gitignore), and lives under src/ rather than public/ so Vite
// can statically bundle it and correctly rewrite its internal
// `fetch(new URL('stockfly_wasm_bg.wasm', import.meta.url))` call.
// @ts-ignore -- generated types, not present until the crate is built.
import init, { StockFlyEngine } from "../wasm-gen/stockfly_wasm.js";

import { quantize, topNeurons, summarizeRegions } from "../brain/activation";
import { parseAnnotations } from "../brain/geometry";

let engine: StockFlyEngine | null = null;
let generation = 0;
let regions: string[] | null = null;
let queue = Promise.resolve();

async function fetchRequired(url: string): Promise<Response> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Failed to load ${url}: HTTP ${response.status}`);
  return response;
}

async function concatBlocks(dir: string, filenames: string[]): Promise<Uint8Array> {
  const parts: Uint8Array[] = [];
  let total = 0;
  for (const name of filenames) {
    const res = await fetch(`${dir}/${name}`);
    if (!res.ok) throw new Error(`failed to fetch ${dir}/${name}: ${res.status}`);
    const buf = new Uint8Array(await res.arrayBuffer());
    parts.push(buf);
    total += buf.length;
  }
  const out = new Uint8Array(total);
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.length;
  }
  return out;
}

async function loadEngine(requestGeneration: number) {
  await init();

  const manifestRes = await fetchRequired("/vendor/graph/manifest.json");
  const manifestText = await manifestRes.text();
  const manifest = JSON.parse(manifestText);

  const neuronsRes = await fetchRequired("/vendor/graph/neurons.bin");
  const offsetsRes = await fetchRequired("/vendor/graph/offsets.bin");
  const neurons = new Uint8Array(await neuronsRes.arrayBuffer());
  const offsets = new Uint8Array(await offsetsRes.arrayBuffer());

  const blocks = [...manifest.edge_blocks].sort((a: { index: number }, b: { index: number }) => a.index - b.index);
  const srcNames = blocks.map((b: { index: number }) => `edge_src_blocks/${String(b.index).padStart(4, "0")}.bin`);
  const weightNames = blocks.map((b: { index: number }) => `edge_weight_blocks/${String(b.index).padStart(4, "0")}.bin`);
  const edgeSrc = await concatBlocks("/vendor/graph", srcNames);
  const edgeWeight = await concatBlocks("/vendor/graph", weightNames);

  const sensoryJson = await (await fetchRequired("/vendor/chess-maps/sensory-map.json")).text();
  const outputJson = await (await fetchRequired("/vendor/chess-maps/output-map.json")).text();

  engine = new StockFlyEngine(manifestText, neurons, offsets, edgeSrc, edgeWeight, sensoryJson, outputJson);

  // Only a genuine 404 means no trained model. Corrupt checkpoints and
  // network failures are actionable load errors, never a silent baseline.
  const checkpointRes = await fetch("/vendor/checkpoints/stockfly-bio-full.sfckpt");
  if (checkpointRes.ok) engine.load_checkpoint(await checkpointRes.text());
  else if (checkpointRes.status !== 404) throw new Error(`Checkpoint HTTP ${checkpointRes.status}`);

  // Annotations are optional for chess inference. The brain panel reports
  // unavailable/corrupt metadata; do not invent regions when it is missing.
  regions = null;
  try {
    const metadata = await (await fetchRequired("/vendor/brain/metadata.json")).json();
    regions = parseAnnotations(metadata, engine.neuron_count(), manifest.neurons_sha256).map(row => row[3]);
  } catch { /* Frames explicitly carry no region summaries without annotations. */ }

  const backend = JSON.parse(await engine.initialize_gpu());

  post({
    type: "loaded",
    generation: requestGeneration,
    manifest: {
      neuronCount: engine.neuron_count(),
      edgeCount: engine.edge_count(),
      graphNeuronsSha256: manifest.neurons_sha256,
      modelLabel: engine.model_label(),
      backend: backend.backend,
      adapter: backend.adapter,
      ...(backend.fallback_reason ? { fallbackReason: backend.fallback_reason } : {}),
    },
  });
}

function post(msg: StockFlyResponse, transfer: Transferable[] = []) {
  (self as unknown as Worker).postMessage(msg, transfer);
}

async function handle(req: Exclude<StockFlyRequest, { type: "reset" }>) {
  if (req.generation !== generation) return;
  try {
    if (req.type === "load") {
      engine?.free();
      engine = null;
      await loadEngine(req.generation);
    } else {
      if (!engine) throw new Error("Engine not loaded yet");
      const settleSteps = req.settleSteps ?? 16;
      if (!Number.isInteger(settleSteps) || settleSteps < 1 || settleSteps > 4096) throw new Error("Invalid settle steps");
      const started = performance.now();
      let lastPosted = -Infinity;
      const raw = await engine.infer_stream(req.fen, settleSteps,
        async (step: number, tMs: number, rates: Float32Array, backend: string) => {
          // Yield between real samples: lets resets cancel CPU and GPU work
          // and limits transferred visualization updates to at most 25 Hz.
          await new Promise(resolve => setTimeout(resolve, Math.max(0, 40 - (performance.now() - lastPosted))));
          if (req.generation !== generation) throw new Error("Obsolete inference");
          const top = topNeurons(rates);
          const regionRates = regions ? summarizeRegions(rates, regions) : [];
          const neuronRates = req.frameMode === "full" ? rates : quantize(rates);
          const buffer = neuronRates instanceof Float32Array ? neuronRates.buffer : neuronRates.values.buffer;
          lastPosted = performance.now();
          post({ type: "frame", generation: req.generation, traceId: req.traceId,
            frame: { step, tMs, elapsedMs: lastPosted - started, backend, neuronRates, topNeurons: top, regionRates } }, [buffer]);
        });
      if (req.generation !== generation) return;
      const result = JSON.parse(raw);
      post({
        type: "decision", generation: req.generation,
        traceId: req.traceId,
        selectedMove: result.selected_move,
        fromRates: result.from_rates,
        toRates: result.to_rates,
        promotionRates: result.promotion_rates,
        settleSteps,
        graphNeuronsSha256: result.graph_neurons_sha256,
        sensoryMapSha256: result.sensory_map_sha256,
        outputMapSha256: result.output_map_sha256,
        backend: result.backend,
        adapter: result.adapter,
        ...(result.gpu_fallback_reason ? { fallbackReason: result.gpu_fallback_reason } : {}),
        modelLabel: result.model_label,
      });
    }
  } catch (e) {
    if (req.generation !== generation) return;
    post({ type: "error", generation: req.generation,
      ...(req.type === "position" ? { traceId: req.traceId } : {}),
      message: e instanceof Error ? e.message : String(e) });
  }
}

self.addEventListener("message", (event: MessageEvent<StockFlyRequest>) => {
  const req = event.data;
  // Invalidate immediately; engine mutation remains strictly serialized.
  if (req.type === "reset") { generation = req.generation; return; }
  if (req.type === "load") generation = req.generation;
  queue = queue.then(() => handle(req));
});
