/// <reference lib="webworker" />
import type { StockFlyRequest, StockFlyResponse } from "./protocol";
// Generated by `wasm-pack build` from crates/stockfly-wasm (see that
// crate's Cargo.toml); this directory is build output, not committed
// (wasm-gen/.gitignore), and lives under src/ rather than public/ so Vite
// can statically bundle it and correctly rewrite its internal
// `fetch(new URL('stockfly_wasm_bg.wasm', import.meta.url))` call.
// @ts-ignore -- generated types, not present until the crate is built.
import init, { StockFlyEngine } from "../wasm-gen/stockfly_wasm.js";

let engine: any = null;

async function concatBlocks(dir: string, filenames: string[]): Promise<Uint8Array> {
  const parts: Uint8Array[] = [];
  let total = 0;
  for (const name of filenames) {
    const res = await fetch(`${dir}/${name}`);
    if (!res.ok) throw new Error(`failed to fetch ${dir}/${name}: ${res.status}`);
    const buf = new Uint8Array(await res.arrayBuffer());
    parts.push(buf);
    total += buf.length;
  }
  const out = new Uint8Array(total);
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.length;
  }
  return out;
}

async function loadEngine() {
  await init();

  const manifestRes = await fetch("/vendor/graph/manifest.json");
  const manifestText = await manifestRes.text();
  const manifest = JSON.parse(manifestText);

  const neuronsRes = await fetch("/vendor/graph/neurons.bin");
  const offsetsRes = await fetch("/vendor/graph/offsets.bin");
  const neurons = new Uint8Array(await neuronsRes.arrayBuffer());
  const offsets = new Uint8Array(await offsetsRes.arrayBuffer());

  const blocks = [...manifest.edge_blocks].sort((a: any, b: any) => a.index - b.index);
  const srcNames = blocks.map((b: any) => `edge_src_blocks/${String(b.index).padStart(4, "0")}.bin`);
  const weightNames = blocks.map((b: any) => `edge_weight_blocks/${String(b.index).padStart(4, "0")}.bin`);
  const edgeSrc = await concatBlocks("/vendor/graph", srcNames);
  const edgeWeight = await concatBlocks("/vendor/graph", weightNames);

  const sensoryJson = await (await fetch("/vendor/chess-maps/sensory-map.json")).text();
  const outputJson = await (await fetch("/vendor/chess-maps/output-map.json")).text();

  engine = new StockFlyEngine(manifestText, neurons, offsets, edgeSrc, edgeWeight, sensoryJson, outputJson);

  // Best-effort: a fresh clone with no checkpoint fetched yet still plays
  // (as the untrained Stage-0 baseline) rather than failing to load.
  try {
    const checkpointRes = await fetch("/vendor/checkpoints/stockfly-bio-full.sfckpt");
    if (checkpointRes.ok) {
      const checkpointJson = await checkpointRes.text();
      engine.load_checkpoint(checkpointJson);
    }
  } catch {
    // No checkpoint available yet -- play as the untrained baseline.
  }

  const backend = JSON.parse(await engine.initialize_gpu());

  post({
    type: "loaded",
    manifest: {
      neuronCount: engine.neuron_count(),
      edgeCount: engine.edge_count(),
      graphNeuronsSha256: manifest.neurons_sha256,
      modelLabel: engine.model_label(),
      backend: backend.backend,
      adapter: backend.adapter,
      ...(backend.fallback_reason ? { fallbackReason: backend.fallback_reason } : {}),
    },
  });
}

function post(msg: StockFlyResponse) {
  (self as unknown as Worker).postMessage(msg);
}

self.addEventListener("message", async (event: MessageEvent<StockFlyRequest>) => {
  const req = event.data;
  try {
    if (req.type === "load") {
      await loadEngine();
    } else if (req.type === "reset") {
      engine = null;
    } else if (req.type === "position") {
      if (!engine) throw new Error("engine not loaded yet");
      const settleSteps = req.settleSteps ?? 16;
      const raw = await engine.infer_async(req.fen, settleSteps);
      const result = JSON.parse(raw);
      post({
        type: "decision",
        traceId: req.traceId,
        selectedMove: result.selected_move,
        fromRates: result.from_rates,
        toRates: result.to_rates,
        promotionRates: result.promotion_rates,
        settleSteps,
        graphNeuronsSha256: result.graph_neurons_sha256,
        sensoryMapSha256: result.sensory_map_sha256,
        outputMapSha256: result.output_map_sha256,
        backend: result.backend,
        adapter: result.adapter,
        ...(result.gpu_fallback_reason ? { fallbackReason: result.gpu_fallback_reason } : {}),
        modelLabel: result.model_label,
      });
    }
  } catch (e) {
    post({ type: "error", message: e instanceof Error ? e.message : String(e) });
  }
});
